name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LEGACY_README_V2.md'
      - 'nuget.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LEGACY_README_V2.md'
      - 'nuget.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src/RESTCountries.NET

    - name: Run unit tests
      run: dotnet test --configuration Release
      working-directory: ./tests/RESTCountries.NET.Tests
